name: 'nfl_analytics'
version: '1.0.0'
config-version: 2

profile: 'nfl_analytics'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nfl_analytics:
    staging:
      +materialized: table
    marts:
      +materialized: table