version: 2

sources:
  - name: nfl_raw
    database: sports-analytics-475802
    schema: nfl_raw
    tables:
      - name: combine
      - name: contracts
      - name: depth_charts
      - name: draft_picks
      - name: ff_opportunity
      - name: ff_playerids
      - name: ff_rankings
      - name: nextgen_stats
      - name: officials
      - name: play_by_play
      - name: player_stats
      - name: players
      - name: rosters
      - name: rosters_weekly
      - name: schedules
      - name: snap_counts
      - name: teams
      - name: trades
      - name: fines